
/*
Name : Rishab Dhamija
Student no: 213223334
EECS 2031 Section M
Assignment : 2
Question: 4

*/

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

//macros ROWS and COLUMNS to store the values for rows adn columsn of the 2-D amin array
#define ROWS 10
#define COLUMNS 10


int main()
{

     //calling srand function to randomize the seed generated for the random pseudo-number generator
     srand(time(NULL));

     //rindex and sindex correspond to the row as well as column indexes used for main_array
     //random_number will store the value generated by the rand() function mod 4
     //data_counter stores the index corresponding to elements of the data array during random walk
     //exit_status determines when there is no more space to walk leading to premature termination
    int rindex,cindex,random_number,data_counter,exit_status;
    rindex = cindex = 0;
    //data_counter is set to 1 since we will initialize the first element of the data array is already passed to the main_array
    data_counter = 1;
     //initially, the exit_status is se to 1 so that while loop below can run at least one time
    exit_status = 1;
    //these values will be stored during random-walk in the 2-D  main_array array
    char data[] = {'A', 'B', 'C', 'D', 'E', 'F',
                   'G', 'H', 'I', 'J', 'K', 'L',
                   'M', 'N', 'O', 'P', 'Q', 'R',
                   'S', 'T', 'U', 'V', 'W', 'X',
                   'Y', 'Z'};
    //this is a 10 x 10 2-D array on which random walk will be done
     char main_array[ROWS][COLUMNS];
     //initializing the main_array elements initially with '.'
     for (int i=0;i< ROWS;i++)
     {
         for(int j=0;j<COLUMNS;j++)
         {
              main_array[i][j] = '.';
         }

     }
     //the random walk will always start from the first element of the array so it can be initialized
     main_array[rindex][cindex] = data[0];

    //we wish to run the loop 25 times as we already initialized the first element of the main_array with the character 'A'
     while(data_counter <26 && exit_status!=0)
     {
         //random_number will hold one value among { 0,1 2,3}
        random_number =  rand() %4;
     //the values of the random_number are distributed as follows:
     //0 - move left
     //1 - move right
     //2 - move up
     //3 - move down
     //first case for moving left
        if(random_number == 0)
        {
             //checking whether space is available in the element to be walked on
            if(main_array[rindex][cindex-1] == '.' && cindex != 0)
            {
                //marking the main_array element with the character
                main_array[rindex][cindex - 1] = data[data_counter];
                data_counter++;
                cindex--;
                //checking whether further space is available for the next iteration to be possible
                if(main_array[rindex][cindex-1] != '.' && main_array[rindex][cindex+1] !='.' && main_array[rindex-1][cindex] !='.' && main_array[rindex+1][cindex] !='.')
                {
                    //exit_status here denotes no space available leading to premature termination
                    exit_status= 0;
                }
                else
                {
                    //exit_status here denotes that space is available
                    exit_status = 1;
                }
                if(exit_status == 0)
                {
                    //premature termination confirmation
                    break;
                }
            }
        }
        //rest of the three cases involve the same set of comments
      //case for moving right
        if(random_number == 1)
        {

            if(main_array[rindex][cindex+1] == '.' && cindex != COLUMNS-1)
            {
                main_array[rindex][cindex + 1] = data[data_counter];
                data_counter++;
                cindex++;
                if(main_array[rindex][cindex-1] != '.' && main_array[rindex][cindex+1] !='.' && main_array[rindex-1][cindex] !='.' && main_array[rindex+1][cindex] !='.')
                {
                    exit_status= 0;
                }
                else
                {
                    exit_status = 1;
                }

                if(exit_status == 0)
                {
                    break;
                }
            }
        }
     //case for moving up
        if(random_number == 2)
        {

            if(main_array[rindex-1][cindex] == '.' && rindex != 0)
            {
                main_array[rindex-1][cindex] = data[data_counter];
                data_counter++;
                rindex--;
                 if(main_array[rindex][cindex-1] != '.' && main_array[rindex][cindex+1] !='.' && main_array[rindex-1][cindex] !='.' && main_array[rindex+1][cindex] !='.')
                {
                    exit_status= 0;
                }
                else
                {
                    exit_status = 1;
                }
                if(exit_status == 0)
                {
                    break;
                }
            }
        }
     //case for moving down
        if(random_number == 3)
        {

            if(main_array[rindex+1][cindex] == '.' && rindex != ROWS-1)
            {
                main_array[rindex+1][cindex] = data[data_counter];
                data_counter++;
                rindex++;
                if(main_array[rindex][cindex-1] != '.' && main_array[rindex][cindex+1] !='.' && main_array[rindex-1][cindex] !='.' && main_array[rindex+1][cindex] !='.')
                {
                    exit_status= 0;
                }
                else
                {
                    exit_status = 1;
                }
                if(exit_status == 0)
                {
                    break;

                }
            }
        }

    }
 //printing the elements of the main_array after the entire random walk
    for (int i=0;i< ROWS;i++)
     {
         for(int j=0;j<COLUMNS;j++)
         {
              printf("%c" ,main_array[i][j]);
         }
         printf("\n");

     }

    return 0;
}

